name: MacOS Monterey Swift Release CI

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:

  exec-mac-ci-release:
    runs-on: [self-hosted, macOS, macStudio] 

    steps:
      #- name: Install guunits
      #  uses: mipalgu/install-guunits@main

      - name: Checkout repo
        uses: actions/checkout@v2
      
      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift

      - name: Release Build
        run: swift build -c release

      - name: Release Test
        run: |
          swift test -c release

      - name: Package Release build
        run: |
          cd Tests/GUUnits
          swift build -c release

